---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
    {{- include "edge-operator.selectorLabels" . | nindent 4 }}
