---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "edge-operator.fullname" . }}-serving-cert
  name: {{ include "edge-operator.fullname" . }}-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-edge-emqx-io-v1alpha1-neuronex
  failurePolicy: Fail
  name: validate.neuronex.edge.emqx.io
  rules:
  - apiGroups:
    - edge.emqx.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - neuronexs
  sideEffects: None
