# permissions for end users to view neuronexs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: neuronex-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edge-operator
    app.kubernetes.io/part-of: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: neuronex-viewer-role
rules:
- apiGroups:
  - edge.emqx.io
  resources:
  - neuronexs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.emqx.io
  resources:
  - neuronexs/status
  verbs:
  - get
