apiVersion: edge.emqx.io/v1alpha1
kind: NeuronEX
metadata:
  labels:
    app.kubernetes.io/name: neuronex
    app.kubernetes.io/instance: neuronex-sample
    app.kubernetes.io/part-of: edge-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: edge-operator
  name: neuronex-sample
spec:
#  publicKeys:
#  - name: sample-secret
#    data: base64encode
  replicas: 1

  volumeClaimTemplate: ## optional
    metadata:
      name: neuronex-sample
      namespace: default
      labels:
        app.kubernetes.io/instance: neuronex-sample
    spec:
      storageClassName: standard
      resources:
        requests:
          storage: 20Mi
      accessModes:
      - ReadWriteOnce
  neuron:
    name: neuron
    image: emqx/neuron:2.3.0
    imagePullPolicy: IfNotPresent ## optional
    readinessProbe:  ## optional
      httpGet:
        path: "/"
        port: 7000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 12
    terminationMessagePath: /dev/termination-log ## optional
    terminationMessagePolicy: File ## optional
  ekuiper:
    name: ekuiper
    image: lfedge/ekuiper:1.7-slim-python
    imagePullPolicy: IfNotPresent ## optional
    livenessProbe:  ## optional
      httpGet:
        path: "/"
        port: 9081
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 12
    terminationMessagePath: /dev/termination-log ## optional
    terminationMessagePolicy: File ## optional
