apiVersion: edge.emqx.io/v1alpha1
kind: EKuiper
metadata:
  labels:
    app.kubernetes.io/name: ekuiper
    app.kubernetes.io/instance: ekuiper-sample
    app.kubernetes.io/part-of: edge-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: edge-operator
  name: ekuiper-sample
spec:
#  publicKeys:
#  - name: sample-secret
#    data: base64encode

  replicas: 1
  # volumeClaimTemplate:
  #   metadata:
  #    name: sample
  #   spec:
  #     accessModes:
  #     - ReadWriteMany
  #     resources:
  #       requests:
  #         storage: 2Gi
  ekuiper:
    name: "ekuiper"
    image: lfedge/ekuiper:1.7-slim-python
    imagePullPolicy: IfNotPresent ## optional
    readinessProbe:  ## optional
      httpGet:
        path: "/"
        port: 9081
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 12
    terminationMessagePath: /dev/termination-log ## optional
    terminationMessagePolicy: File ## optional
