name: Release emqx operator

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ github.repository_owner }}/edge-operator-controller
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - uses: docker/login-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .
    - name: install kubebuilder
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m | sed 's/x86_64/amd64/')
        curl -fsL "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.16.4-${OS}-${ARCH}.tar.gz" -o kubebuilder-tools
        tar -zxvf kubebuilder-tools
        sudo mv kubebuilder/ /usr/local/kubebuilder
    - id: generate_yaml
      run: |
        make kustomize
        cd config/manager && ./bin/kustomize edit set image controller="${{ github.repository_owner }}/edge-operator-controller:${{ github.ref_name }}"
        ./bin/kustomize build config/default > edge-operator.yaml
        echo "file=edge-operator.yaml" >> $GITHUB_OUTPUT
    - id: prerelease
      run: |
        if echo "${{ github.ref_name }}" |egrep -q "^[0-9].[0-9].[0-9]$"; then
          echo "prerelease=false" >> $GITHUB_OUTPUT
        else
          echo "prerelease=true" >> $GITHUB_OUTPUT
        fi
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ steps.prerelease.outputs.prerelease }}
        token: ${{ github.token }}
        name: Edge Operator ${{ github.ref_name }} Released
        body_path: RELEASE.md
        generate_release_notes: true
        files: |
          ${{ steps.generate_yaml.outputs.file }}
